const COUNTRY_CODES = {
  "Afghanistan": "AF",
  "Albania": "AL",
  "Algeria": "DZ",
  "Andorra": "AD",
  "Angola": "AO",
  "Antigua and Barbuda": "AG",
  "Argentina": "AR",
  "Armenia": "AM",
  "Australia": "AU",
  "Austria": "AT",
  "Azerbaijan": "AZ",
  "Bahamas": "BS",
  "Bahrain": "BH",
  "Bangladesh": "BD",
  "Barbados": "BB",
  "Belarus": "BY",
  "Belgium": "BE",
  "Belize": "BZ",
  "Benin": "BJ",
  "Bhutan": "BT",
  "Bolivia": "BO",
  "Bosnia and Herzegovina": "BA",
  "Botswana": "BW",
  "Brazil": "BR",
  "Brunei": "BN",
  "Bulgaria": "BG",
  "Burkina Faso": "BF",
  "Burundi": "BI",
  "Cabo Verde": "CV",
  "Cambodia": "KH",
  "Cameroon": "CM",
  "Canada": "CA",
  "Central African Republic": "CF",
  "Chad": "TD",
  "Chile": "CL",
  "China": "CN",
  "Colombia": "CO",
  "Comoros": "KM",
  "Congo": "CG",
  "Costa Rica": "CR",
  "Cote d'Ivoire": "CI",
  "Croatia": "HR",
  "Cuba": "CU",
  "Cyprus": "CY",
  "Czechia": "CZ",
  "Democratic Republic of the Congo": "CD",
  "Denmark": "DK",
  "Djibouti": "DJ",
  "Dominica": "DM",
  "Dominican Republic": "DO",
  "Ecuador": "EC",
  "Egypt": "EG",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  "Eritrea": "ER",
  "Estonia": "EE",
  "Eswatini": "SZ",
  "Ethiopia": "ET",
  "Fiji": "FJ",
  "Finland": "FI",
  "France": "FR",
  "Gabon": "GA",
  "Gambia": "GM",
  "Georgia": "GE",
  "Germany": "DE",
  "Ghana": "GH",
  "Greece": "GR",
  "Grenada": "GD",
  "Guatemala": "GT",
  "Guinea": "GN",
  "Guinea-Bissau": "GW",
  "Guyana": "GY",
  "Haiti": "HT",
  "Honduras": "HN",
  "Hungary": "HU",
  "Iceland": "IS",
  "India": "IN",
  "Indonesia": "ID",
  "Iran": "IR",
  "Iraq": "IQ",
  "Ireland": "IE",
  "Israel": "IL",
  "Italy": "IT",
  "Jamaica": "JM",
  "Japan": "JP",
  "Jordan": "JO",
  "Kazakhstan": "KZ",
  "Kenya": "KE",
  "Kiribati": "KI",
  "Kuwait": "KW",
  "Kyrgyzstan": "KG",
  "Laos": "LA",
  "Latvia": "LV",
  "Lebanon": "LB",
  "Lesotho": "LS",
  "Liberia": "LR",
  "Libya": "LY",
  "Liechtenstein": "LI",
  "Lithuania": "LT",
  "Luxembourg": "LU",
  "Madagascar": "MG",
  "Malawi": "MW",
  "Malaysia": "MY",
  "Maldives": "MV",
  "Mali": "ML",
  "Malta": "MT",
  "Marshall Islands": "MH",
  "Mauritania": "MR",
  "Mauritius": "MU",
  "Mexico": "MX",
  "Micronesia": "FM",
  "Moldova": "MD",
  "Monaco": "MC",
  "Mongolia": "MN",
  "Montenegro": "ME",
  "Morocco": "MA",
  "Mozambique": "MZ",
  "Myanmar": "MM",
  "Namibia": "NA",
  "Nauru": "NR",
  "Nepal": "NP",
  "Netherlands": "NL",
  "New Zealand": "NZ",
  "Nicaragua": "NI",
  "Niger": "NE",
  "Nigeria": "NG",
  "North Korea": "KP",
  "North Macedonia": "MK",
  "Norway": "NO",
  "Oman": "OM",
  "Pakistan": "PK",
  "Palau": "PW",
  "Palestine": "PS",
  "Panama": "PA",
  "Papua New Guinea": "PG",
  "Paraguay": "PY",
  "Peru": "PE",
  "Philippines": "PH",
  "Poland": "PL",
  "Portugal": "PT",
  "Qatar": "QA",
  "Romania": "RO",
  "Russia": "RU",
  "Rwanda": "RW",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Vincent and the Grenadines": "VC",
  "Samoa": "WS",
  "San Marino": "SM",
  "Sao Tome and Principe": "ST",
  "Saudi Arabia": "SA",
  "Senegal": "SN",
  "Serbia": "RS",
  "Seychelles": "SC",
  "Sierra Leone": "SL",
  "Singapore": "SG",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "Solomon Islands": "SB",
  "Somalia": "SO",
  "South Africa": "ZA",
  "South Korea": "KR",
  "South Sudan": "SS",
  "Spain": "ES",
  "Sri Lanka": "LK",
  "Sudan": "SD",
  "Suriname": "SR",
  "Sweden": "SE",
  "Switzerland": "CH",
  "Syria": "SY",
  "Tajikistan": "TJ",
  "Tanzania": "TZ",
  "Thailand": "TH",
  "Timor-Leste": "TL",
  "Togo": "TG",
  "Tonga": "TO",
  "Trinidad and Tobago": "TT",
  "Tunisia": "TN",
  "Turkey": "TR",
  "Turkmenistan": "TM",
  "Tuvalu": "TV",
  "Uganda": "UG",
  "Ukraine": "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  "Uruguay": "UY",
  "Uzbekistan": "UZ",
  "Vanuatu": "VU",
  "Vatican City": "VA",
  "Venezuela": "VE",
  "Vietnam": "VN",
  "Yemen": "YE",
  "Zambia": "ZM",
  "Zimbabwe": "ZW",
};

const COUNTRY_ALIASES = {
  "United Arab Emirates": ["uae", "dubai", "abu dhabi", "sharjah"],
  "India": [
    "mumbai",
    "delhi",
    "new delhi",
    "bangalore",
    "bengaluru",
    "goa",
    "bharat",
    "maharashtra",
    "karnataka",
    "tamil nadu",
    "gujarat",
    "rajasthan",
    "west bengal",
    "uttar pradesh",
    "telangana",
    "kerala",
    "punjab",
    "haryana",
    "hyderabad",
    "chennai",
    "kolkata",
    "pune",
    "jaipur",
    "ahmedabad",
  ],
  "United States": [
    "usa",
    "us",
    "america",
    "new york",
    "los angeles",
    "california",
    "texas",
    "florida",
    "illinois",
    "pennsylvania",
    "ohio",
    "georgia",
    "north carolina",
    "michigan",
    "new jersey",
    "virginia",
    "washington state",
    "washington",
    "arizona",
    "massachusetts",
    "tennessee",
    "indiana",
    "missouri",
    "maryland",
    "colorado",
    "minnesota",
    "wisconsin",
    "south carolina",
    "alabama",
    "louisiana",
    "kentucky",
    "oregon",
    "oklahoma",
    "connecticut",
    "utah",
    "nevada",
    "iowa",
    "district of columbia",
    "washington dc",
    "dc",
  ],
  "United Kingdom": ["uk", "england", "britain", "great britain", "london", "scotland", "wales", "northern ireland"],
  "France": ["paris", "schengen", "eu schengen"],
  "Italy": ["rome", "venice", "milan", "schengen"],
  "Germany": ["berlin", "munich", "schengen"],
  "Spain": ["madrid", "barcelona", "schengen"],
  "Netherlands": ["amsterdam", "holland", "schengen"],
  "Switzerland": ["zurich", "geneva", "schengen"],
  "Japan": ["tokyo", "osaka", "kyoto"],
  "Thailand": ["bangkok", "phuket", "pattaya"],
  "Singapore": ["singapura"],
  "Turkey": ["istanbul"],
  "Saudi Arabia": ["riyadh", "jeddah", "makkah", "mecca", "madinah", "medina"],
  "South Korea": ["korea", "seoul"],
};

const normalize = (value) =>
  String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

const codeToFlagEmoji = (code) =>
  String(code || "")
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));

const isFlagEmoji = (value) => /^\p{Regional_Indicator}{2}$/u.test(String(value || ""));

export const getCountryFlagEmoji = (countryName, fallback) => {
  const code = COUNTRY_CODES[countryName];
  if (code) return codeToFlagEmoji(code);
  return isFlagEmoji(fallback)  fallback : "🌍";
};

/** ISO 3166-1 alpha-2 when the canonical English name matches our map */
export const getIsoAlpha2FromCountryName = (countryName) =>
  COUNTRY_CODES[countryName] || null;

/** Top-left code chip on cards: real ISO when known (avoids slug quirks like "ca" from "canada"). */
export const getCountryCardCodeBadge = (country) => {
  const iso = country.name  getIsoAlpha2FromCountryName(country.name) : null;
  if (iso) return iso;
  const id = String(country.id || "").replace(/[^a-z0-9]/gi, "");
  if (id.length >= 2) return id.slice(0, 2).toUpperCase();
  return "--";
};

export const matchesCountrySearch = (country, rawTerm) => {
  const term = normalize(rawTerm);
  if (!term) return true;

  const values = [
    country.name,
    country.id,
    country.slug,
    country.continent,
    country.visaType,
  ].map(normalize);

  if (term.length >= 2) {
    values.push(...(COUNTRY_ALIASES[country.name] || []).map(normalize));
  }

  return values.some((value) => value.includes(term));
};

export const getCountrySearchHint = (country, rawTerm) => {
  const term = normalize(rawTerm);
  if (!term) return "";

  const alias = (COUNTRY_ALIASES[country.name] || []).find((value) =>
    normalize(value).includes(term)
  );

  return alias  `Matches ${alias}` : "";
};
